<?php
/**
 * Sector-aware icon registry.
 *
 * Maps the emoji characters stored in `categories.icon` (the legacy format)
 * to local PNG files from Microsoft's Fluent Emoji 3D pack
 * (github.com/microsoft/fluentui-emoji, MIT licensed).
 *
 * Structure: [sector_code => [emoji => relative_filename_without_ext]]
 *
 * The `icon` column in DB continues storing the emoji character,
 * so existing categories keep working without migration. When we render,
 * if the emoji exists in the map we swap it for the local PNG.
 * Otherwise we fall back to the emoji itself.
 *
 * Emoji order matches the per-sector palettes in
 * `functions.php::categoryIconPalette()`.
 */

return [
    'restaurant' => [
        '🍽️' => 'fork-plate',
        '🥗' => 'salad',
        '🍔' => 'burger',
        '🍕' => 'pizza',
        '🍝' => 'spaghetti',
        '🥙' => 'flatbread',
        '🍗' => 'poultry',
        '🥘' => 'pan',
        '🍲' => 'pot',
        '🥪' => 'sandwich',
        '🌮' => 'taco',
        '🍰' => 'shortcake',
        '🍦' => 'icecream',
        '🍩' => 'doughnut',
        '🍪' => 'cookie',
        '☕'  => 'coffee',
        '🥤' => 'soda',
        '🧃' => 'juice',
        '🍹' => 'tropical',
        '🍷' => 'wine',
        '🥟' => 'dumpling',
        '🍜' => 'noodles',
        '🍱' => 'bento',
        '🥠' => 'fortunecookie',
        '🍤' => 'shrimp-fried',
        '🦐' => 'shrimp',
        '🥞' => 'pancakes',
        '🧇' => 'waffle',
        '🍳' => 'egg',
        '🥓' => 'bacon',
    ],

    'sweets' => [
        '🧁' => 'cupcake',
        '🍰' => 'shortcake',
        '🎂' => 'birthday-cake',
        '🍪' => 'cookie',
        '🍩' => 'doughnut',
        '🍫' => 'chocolate',
        '🍬' => 'candy',
        '🍭' => 'lollipop',
        '🍮' => 'custard',
        '🍯' => 'honey',
        '🍨' => 'icecream-bowl',
        '🍧' => 'shaved-ice',
        '🍡' => 'dango',
        '🥮' => 'mooncake',
        '🥧' => 'pie',
        '🍓' => 'strawberry',
        '🍒' => 'cherries',
        '🫐' => 'blueberries',
        '🥝' => 'kiwi',
        '🥥' => 'coconut',
        '🍑' => 'peach',
        '🍍' => 'pineapple',
        '🥜' => 'peanuts',
        '🍌' => 'banana',
        '🍎' => 'apple',
        '☕'  => 'coffee',
        '🥤' => 'soda',
        '🧃' => 'juice',
        '🍵' => 'tea',
        '🧋' => 'bubble-tea',
    ],

    'grocery' => [
        '🛒' => 'cart',
        '🥖' => 'baguette',
        '🍞' => 'bread',
        '🥩' => 'meat',
        '🧀' => 'cheese',
        '🥚' => 'egg',
        '🥛' => 'milk',
        '🥫' => 'canned',
        '🥦' => 'broccoli',
        '🥕' => 'carrot',
        '🍅' => 'tomato',
        '🍎' => 'apple',
        '🍌' => 'banana',
        '🍇' => 'grapes',
        '🥔' => 'potato',
        '🧅' => 'onion',
        '🧄' => 'garlic',
        '🍉' => 'watermelon',
        '🌽' => 'corn',
        '🍚' => 'rice',
        '🍝' => 'pasta',
        '🥜' => 'peanuts',
        '🍯' => 'honey',
        '🧈' => 'butter',
        '🥓' => 'bacon',
        '🍗' => 'poultry',
        '🍖' => 'meat-bone',
        '🍤' => 'shrimp',
        '🧴' => 'lotion',
        '🧻' => 'tissue',
    ],

    'clothing' => [
        '👕' => 'tshirt',
        '👔' => 'necktie',
        '👗' => 'dress',
        '👖' => 'jeans',
        '🧥' => 'coat',
        '🧣' => 'scarf',
        '🧤' => 'gloves',
        '🧦' => 'socks',
        '👙' => 'bikini',
        '👘' => 'kimono',
        '🥻' => 'sari',
        '🧢' => 'cap',
        '👒' => 'hat-woman',
        '🎩' => 'top-hat',
        '👞' => 'shoe-mans',
        '👟' => 'sneaker',
        '👠' => 'heels',
        '👡' => 'sandal',
        '👢' => 'boot',
        '🎽' => 'jersey',
        '💍' => 'ring',
        '👜' => 'handbag',
        '👛' => 'clutch',
        '🧳' => 'luggage',
        '🕶️' => 'sunglasses',
        '🎒' => 'backpack',
        '👚' => 'blouse',
        '🥼' => 'labcoat',
        '🦺' => 'vest',
        '🧸' => 'teddy',
    ],

    'phones' => [
        '📱' => 'phone',
        '📟' => 'pager',
        '☎️' => 'telephone',
        '📞' => 'receiver',
        '⌚' => 'watch',
        '🎧' => 'headphones',
        '🎙️' => 'mic',
        '🔌' => 'plug',
        '🔋' => 'battery',
        '💾' => 'floppy',
        '💿' => 'disc',
        '📷' => 'camera',
        '📸' => 'camera-flash',
        '📹' => 'videocam',
        '📺' => 'tv',
        '🎮' => 'gamepad',
        '🕹️' => 'joystick',
        '🖥️' => 'desktop',
        '💻' => 'laptop',
        '🖨️' => 'printer',
        '🖱️' => 'mouse',
        '⌨️' => 'keyboard',
        '📻' => 'radio',
        '🎚️' => 'slider',
        '🎛️' => 'knobs',
        '🔦' => 'flashlight',
        '💡' => 'bulb',
        '🛜' => 'power',
        '📡' => 'antenna',
        '🔧' => 'wrench',
    ],

    'electronics' => [
        '💻' => 'laptop',
        '🖥️' => 'desktop',
        '📱' => 'phone',
        '📷' => 'camera',
        '📹' => 'videocam',
        '🎥' => 'movie',
        '🎤' => 'mic-voice',
        '🎧' => 'headphones',
        '🎮' => 'gamepad',
        '🕹️' => 'joystick',
        '⌚' => 'watch',
        '📺' => 'tv',
        '📻' => 'radio',
        '🎙️' => 'mic-studio',
        '🔌' => 'plug',
        '🔋' => 'battery',
        '💡' => 'bulb',
        '💿' => 'disc',
        '📀' => 'dvd',
        '💾' => 'floppy',
        '📟' => 'pager',
        '🖨️' => 'printer',
        '🖱️' => 'mouse',
        '⌨️' => 'keyboard',
        '📡' => 'antenna',
        '🛜' => 'antenna',
        '🔦' => 'flashlight',
        '🧯' => 'extinguisher',
        '⚡' => 'zap',
        '🔧' => 'wrench',
    ],

    'appliances' => [
        '🔌' => 'plug',
        '🔋' => 'battery',
        '💡' => 'bulb',
        '🚿' => 'shower',
        '🛁' => 'bathtub',
        '🛋️' => 'couch',
        '🛏️' => 'bed',
        '🪑' => 'chair',
        '🪞' => 'mirror',
        '🪟' => 'window',
        '🪠' => 'plunger',
        '🧺' => 'basket',
        '🧹' => 'broom',
        '🧽' => 'sponge',
        '🧴' => 'lotion',
        '🪒' => 'razor',
        '🧼' => 'soap',
        '❄️' => 'snowflake',
        '🔥' => 'fire',
        '🌡️' => 'thermometer',
        '⏰' => 'alarm-clock',
        '🕰️' => 'mantel-clock',
        '🔑' => 'key',
        '📦' => 'package',
        '🪣' => 'bucket',
        '🛒' => 'cart',
        '🗑️' => 'trash',
        '🧊' => 'ice',
        '🧯' => 'extinguisher',
        '🪜' => 'ladder',
    ],

    'cars' => [
        '🚗' => 'car',
        '🚙' => 'suv',
        '🚕' => 'taxi',
        '🏎️' => 'racing',
        '🚓' => 'police',
        '🚑' => 'ambulance',
        '🚒' => 'firetruck',
        '🚐' => 'minibus',
        '🛻' => 'pickup',
        '🚚' => 'truck',
        '🚛' => 'lorry',
        '🚜' => 'tractor',
        '🏍️' => 'motorcycle',
        '🛵' => 'scooter-motor',
        '🚲' => 'bicycle',
        '🛴' => 'kick-scooter',
        '🛺' => 'auto-rickshaw',
        '🚌' => 'bus',
        '🚎' => 'trolleybus',
        '⛽' => 'fuel',
        '🔧' => 'wrench',
        '🔩' => 'nut-bolt',
        '🛞' => 'gear',
        '🪫' => 'battery',
        '🔋' => 'battery',
        '🚨' => 'police-light',
        '🏁' => 'flag',
        '🛠️' => 'tools',
        '🔑' => 'key',
        '🗝️' => 'old-key',
    ],

    // Bookstore — Fluent PNG slugs (fallback to raw emoji if file missing).
    // PNGs may be added later in assets/icons/categories/bookstore/<slug>.png
    'bookstore' => [
        '📚' => 'books',
        '📖' => 'open-book',
        '📕' => 'red-book',
        '📗' => 'green-book',
        '📘' => 'blue-book',
        '📙' => 'orange-book',
        '📓' => 'notebook',
        '📔' => 'notebook-decorative',
        '📒' => 'ledger',
        '📰' => 'newspaper',
        '🗞️' => 'rolled-newspaper',
        '📜' => 'scroll',
        '📃' => 'page-curl',
        '📄' => 'page',
        '📑' => 'bookmark-tabs',
        '✏️' => 'pencil',
        '🖊️' => 'pen',
        '🖋️' => 'fountain-pen',
        '✒️' => 'black-nib',
        '📝' => 'memo',
        '📐' => 'triangular-ruler',
        '📏' => 'straight-ruler',
        '🔖' => 'bookmark',
        '🏷️' => 'label',
        '🎓' => 'graduation-cap',
        '🌍' => 'globe-africa',
        '🌎' => 'globe-americas',
        '🔬' => 'microscope',
        '🔭' => 'telescope',
        '🧮' => 'abacus',
    ],
];
